apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
  namespace: canary-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      track: canary
  template:
    metadata:
      labels:
        app: myapp
        track: canary
    spec:
      containers:
        - name: app
          image: ${{secrets.DOCKERHUB_USERNAME}}/canary-demo-pipeline:latest
          ports:
            - containerPort: 3000